### ISSUE TITLE
ability to specify health_check_interval for redis

### ISSUE THREAD

**Issue by L1ghtman2k** [jazzband/django-redis#425]
I am currently running in issue where my Django web app periodically loses connection with my Redis. This seems due to the issue discussed in https://github.com/andymccurdy/redis-py/issues/1140

something like the health_check_interval option would allow such a connection failure to be fixed.

**Comment by L1ghtman2k** [comment]
Will reopen after a bit more research

**Comment by James-Quigley** [comment]
Also would like the ability to pass this kwarg, or maybe just arbitrary kwargs through to the redis-py connection

**Comment by esp4ik** [comment]
+1

**Comment by WisdomPill** [comment]
Hello!

It is already possible to pass `**kwargs` to `py-redis` client.

Since when a connection has to be made in `ConnectionFactory` the `REDIS_CLIENT_KWARGS` are passed to `Redis` client.

You can do it with the following setting

```python
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://localhost:6379',
        'OPTIONS': {
            "REDIS_CLIENT_KWARGS": {"health_check_interval": 30}
        }
    }
}
```

I am closing this, feel free to reopen if my answer did not help you
