### ISSUE TITLE
cannot import name 'get_cache' from 'django.core.cache'

### ISSUE THREAD

**Issue by jianghong3** [jazzband/django-redis#461]
python 3.7.7
django 2.2.1
django-redis 3.8.4

Traceback (most recent call last):
  File "C:\Users\j84167251\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\j84167251\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\j84167251\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\HRDI_HZ\HRDI\resignation_app\views.py", line 52, in index_chart
    cache.set("name", "jh")
  File "C:\Users\j84167251\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\cache\__init__.py", line 98, in __getattr__
    return getattr(caches[DEFAULT_CACHE_ALIAS], name)
  File "C:\Users\j84167251\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\cache\__init__.py", line 79, in __getitem__
    cache = _create_cache(alias)
  File "C:\Users\j84167251\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\cache\__init__.py", line 53, in _create_cache
    "Could not find backend '%s': %s" % (backend, e))
django.core.cache.backends.base.InvalidCacheBackendError: Could not find backend 'django_redis.cache.RedisCache': cannot import name 'get_cache' from 'django.core.cache' (C:\Users\j84167251\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\cache\__init__.py)

**Comment by jdufresne** [comment]
Can you link to a minimal project that demonstrates the issue with djang-redis?

**Comment by JRileyH** [comment]
I too am seeing this error with django 3.1
Working on minimal repro now.

**Comment by JRileyH** [comment]
Actually I spoke too soon...
I fixed this issue by hiking the django-redis version from 3.8.4 (default from pip) to 4.12.1 and don't seem to experience any other issues with the upgrade.

Since my issue is solved I don't feel the need to build out a repro case but will leave this here for others if upgrading is an option for you.

**Comment by jdufresne** [comment]
> I fixed this issue by hiking the django-redis version from 3.8.4 (default from pip) 

What do you mean by this? Doesn't pip default to the latest available version, which it currently lists as 4.12.1. What is this other default version?

https://pypi.org/project/django-redis/#history

**Comment by JRileyH** [comment]
You're right. I didn't check pypi. Sorry perhaps its got to do with pipenv...

But in a fresh project if I run:
```pipenv install django-redis```
It adds:
```django-redis = "*"```
to Pipfile

Then if I run:
```pipenv run pip freeze```
I see an entry for:
```django-redis==3.8.4```

I'm not sure why but it must be some localized issue because in a fresh project pip installs the correct version. ¯\_(ツ)_/¯
Apologies for the confusion but the update stands, upgrading from 3.8.4 solved the `get_cache` issue.

**Comment by kirimaks** [comment]
Do you guys know some way to properly initialize django-redis backend on start?

I'm getting similar exceptions:
```
ImportError Module "django_redis.serializers.pickle" does not define a "PickleSerializer" attribute/class
```

But this exception from django management command. When command starts, then from `handle()` new process started and from that process there is a query to the cache. That exception is thrown on query.
It helps if I add some random cache query before new process is started, so I guess the problem is that cache is kind of lazy and getting initialized in separated process in my case.

So is there some good way to initialize cache when django management command starts?

**Comment by kirimaks** [comment]
@WisdomPill thanks, I think I figured it out. I have 2 processes started from my management command. And the error comes up when processes starting simultaneously. I changed the code to start them one by one and it works fine.

**Comment by TarikMadd** [comment]
Upgrade django-redis library to the latest version

**Comment by WisdomPill** [comment]
@jianghong3 I would close the issue soon if there are no answers on whether and/or how did you solve it, it became kind of an old issue.

**Comment by jdufresne** [comment]
Yeah, this looks like an error in the environment.

**Comment by ericooliveira-mb** [comment]
I getting this error with Django==2.1.2 and Django-redis==3.8.4.
And i can't fix.
