### ISSUE TITLE
How do I force expire specific cache if it is private?

### ISSUE THREAD

**Issue by rfschubert** [jazzband/django-redis#479]
Django has option to cache data privately using:

```python
from django.views.decorators.cache import cache_control
@cache_control(private=True)
class MyView...
```

How can I know and expire the specific cache if another script or server update something and that view would need catch a new version of it without delete the entire cache?

Look, I'm looking to cache some client history but it can change suddenly if another client interact with him, so I would need set a new version to that cache, but how should I do this with `django-redis`?

**Comment by WisdomPill** [comment]
Hello @rfschubert,

`cache_control` does not interact with the django cache itself, it just adds a header to the response so that the browser knows that this page does not change so it will cache it and next time a client asks for it it uses the locally stored page.

As of the `private` attribute it is one possible attribute of the header `Cache-Control`.
In your case I do not think using `cache_control` helps, you should just store the information of the user in cache if the query you are performing is too expensive. You could use `django-redis` for sure or any other cache for that matter.
Your choice if you want to store the whole page or just the data that you are fetching from the database. 
In this case you control on a request basis when to change the content.

I personally recommend to test it, because sometime caching is not really important if your website does not have much traffic and there is no visible difference in using the cache or not.

Did I answer your question?

**Comment by WisdomPill** [comment]
@rfschubert please answer otherwise I will just close the issue since it is not a real issue/bug report and therefore should be asked in stack overflow or similar site/forum

**Comment by rfschubert** [comment]
Thanks for the response, yeah, you helped a lot! I'll close the issue
