### ISSUE TITLE
Close method does nothing by default and undocumented setting.

### ISSUE THREAD

**Issue by AnesFoufa** [jazzband/django-redis#495]
Hi everyone. The method close in DefaultClient does nothing unless the setting DJANGO_REDIS_CLOSE_CONNECTION is at True, in this case, it closes its connection pool as it can be seen here:
https://github.com/jazzband/django-redis/blob/a7ca6e40fd487016cac819cc00ab19286bf3f063/django_redis/client/default.py#L569
I wonder why the closing of the connection pool is not the default behavior and why DJANGO_REDIS_CLOSE_CONNECTION is not documented.
The current behavior causes a great number of unneeded open connections to redis.
I suggest to remove DJANGO_REDIS_CLOSE_CONNECTION and to close the connections or at least, to document this setting if it is to remain.

**Comment by WisdomPill** [comment]
Hello @AnesFoufa maybe we can ask @niwinz if he can answer.

Otherwise I would suggest to at least document the option and maybe with the opinion of some other developers to like @jdufresne for example to make it true by default.

I would vote to make it true by default, if you agree thumbs up, if not thumbs down

**Comment by pinoatrome** [comment]
:+1:

**Comment by pinoatrome** [comment]
Hallo @WisdomPill ,
the PR #496  submitted yesterday closes this issue:  changed implementation, tests and linting are OK BUT the checks fail with a weird error:

> ERROR:   py36-dj22-redislatest: commands failed

anyone with a clue about this?
Thanks
GG

https://github.com/jazzband/django-redis/pull/496/checks?check_run_id=1708842928

**Comment by folt** [comment]
I have been trying for a long time to find the problem why my celery workers freeze without any error signs. It turned out that this was due to the sweating of the radish compound. I think when there is no connection, a connection error exception should occur.

**Comment by pinoatrome** [comment]
> my celery workers freeze without any error signs
that's bad: is it anything that can be connected to django-redis classes?

 > when there is no connection, a connection error exception should occur
Do you mean in the close() method?

**Comment by WisdomPill** [comment]
> I have been trying for a long time to find the problem why my celery workers freeze without any error signs. It turned out that this was due to the sweating of the radish compound. I think when there is no connection, a connection error exception should occur.

I do not think that `django-redis` is related to you `celery` issue, if not please show why you think it is like you said.
As a matter of fact, this issue is about closing the connections, not opening them. 
Furthermore, when opening a connection `django-redis` does no silencing of exceptions. 
I recommend to go to `celery` repository to talk about your `celery` issue.

**Comment by folt** [comment]
> Hi @folt
> 
> > my celery workers freeze without any error signs
> 
> that's bad: is it anything that can be connected to django-redis classes?
> 
> > when there is no connection, a connection error exception should occur
> 
> Do you mean this should happen in the close() method?

For some reason, the settings
`SOCKET_CONNECT_TIMEOUT`
`SOCKET_TIMEOUT`
not fixed by default. So my app froze. This is very difficult to track down. Problems appeared only at the moment of loss of connection, and this happened every 2-3 months. If you set these settings, then the application raises an exception and breaks the connections. Perhaps you just need to set them by default, then the behavior described in the thread can be avoided.

**Comment by pinoatrome** [comment]
I see,
congrats for tracking down this scenario (in production and happening rarely). 
As stated by @WisdomPill  back in the thread these settings are configured in CACHES settings and are passed as args to the client class constructor ("redis.client.Redis") 
The default values per Redis client class are socket_timeout=None, socket_connect_timeout=None so the current implementation in `django-redis` seems to respect this (plus allowing for easy change or even pluggable client).
