### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by laurentL** [jazzband/django-redis#522]
Hi,
is it possible to package a new version with the sentinel protocol ?

Thanks a lot

**Comment by WisdomPill** [comment]
Hello @laurentL do you mean a wheel package?

**Comment by laurentL** [comment]
yes on pypi

**Comment by WisdomPill** [comment]
for release I still do not know how to do them and need permission for that, I think @jdufresne can help with that since he made the last release.

Before releasing I still have to write release notes, to solve issue #509.

@jdufresne can you release a new version after I ping you here when I will sort out the last things to add before a new release?

In the meantime @laurentL if you are in a hurry I suggest to build your own when package or copy `django_redis` in your project like if it is a package of your application.

**Comment by jdufresne** [comment]
@WisdomPill I don't mind doing another release. Please ping me when ready.

**Comment by abdelwahebmoalla** [comment]
Thank you guys for your hard work, any estimated time of the new release? @WisdomPill

**Comment by WisdomPill** [comment]
Sorry, I have not been working on the project lately, this weekend I need to change the CHANGELOG and then we can deploy.

**Comment by WisdomPill** [comment]
Hey, @jdufresne!

I just merged the `CHANGELOG`. 
Can you take care of the release? 
I thought to make it `5.0.0` since there are a lot of changes

**Comment by jdufresne** [comment]
This is now done. Thanks everyone for the contributions!

@WisdomPill I would like this to be the last release I manage so please let me know what you need from me to make future releases possible from yourself or other Jazzband members and I'm happy to follow through with it.

**Comment by WisdomPill** [comment]
yes, in #512 @terencehonles started the PR a GitHub action for releases, @jdufresne can you help there?
